### PR TITLE
Added logs and benchmark

### PR DESCRIPTION
**Pull request by evis-e**

### CODE REVIEW

**Review by mustiikhalil — APPROVED** [review]
Looks good! but benchmark will only return the the time and not the last link. so we can't really work with it. Maybe we can use it to benchmark the performance of our indexer

**Comment by evis-e** [comment]
I added more logging to keep track of the URLs that have been indexed so far. This way if our indexer ever crashes for any reason, we will know where to resume from. Any other suggestions to what kind of logging might be useful?

**Review by mustiikhalil — APPROVED** [review]
GJ

**Review by mustiikhalil — APPROVED** [review]
Looks good to me!

**Pull request merged**
